<?php if (null !== $this->messages && is_array($this->messages) && count($this->messages) >0) : ?>
    <?php foreach ($this->messages as $key => $message) : ?>
        <?php if (! is_string($key)) : ?>
        <div class="alert alert-info" role="alert"><?php echo $this->translate($message)?></div>
        <?php else: ?>
        <div class="alert alert-<?php echo $key?>" role="alert"><?php echo $this->translate($message); ?></div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>