<?php
/** @var \Laminas\Form\FormInterface $form */
$form = $this->form;
/** @var bool $status */
$status = $this->status;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');
$form->setAttribute('autocomplete', 'off');
?>
<div class="container">
    <div class="row">
        <div class="col">
            <h1><?php echo $this->translate('Change Password');?></h1>
            <?php if ($status === true) : ?>
                <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
            <?php elseif ($status === false) : ?>
                <div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
            <?php endif; ?>
        </div>
    </div>
    <?php if (null !== $this->messages && count($this->messages) >0): ?>
        <div class="row">
            <div class="col">
                <?php foreach ($this->messages as $message): ?>
                    <p><?= $message ?></p>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col">
            <?php echo $this->partial('lmcuser::_form.phtml')?>
        </div>
    </div>
</div>
